name: radio_player
description: Play your favorite FM&#x2F;AM radio stations

version: 1.0.0+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.1
  share: ^0.6.3+5
  uuid: ^2.0.4
  just_audio: ^0.0.6
  audio_service: ^0.5.7
  path_provider: ^1.5.1
  provider: ^4.0.2
  google_fonts: ^0.2.0
  http: ^0.12.0+3
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
